# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get Files
        run: git clone https://github.com/wwsq1149/pool
      - name: Get Proxies
        run: D:\a\pool\pool\GetFreeProxies.exe
      - name: HTTP Proxies
        run: type D:\a\pool\pool\Proxy\http.txt
      - name: Get Useful Proxies
        run: D:\a\pool\pool\pf.exe http 15 1000 Proxy\http.txt Proxy\http-pf.txt
      - name: Useful HTTP Proxies
        run: type D:\a\pool\pool\Proxy\http-pf.txt
